# translation of nl.po to Nederlansd
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Antoon Tolboom <atolboo@gmail.com>, 2009.
msgid ""
msgstr ""
"Project-Id-Version: nl\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2008-09-16 10:05+0300\n"
"PO-Revision-Date: 06/11/09 13:13\n"
"Last-Translator: Antoon Tolboom <atolboo@gmail.com>\n"
"Language-Team: Nederlansd <kde-i18n-nl@kde.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: KBabel 1.11.4\n"
"Plural-Forms:  nplurals=2; plural=(n != 1);\n"

#: avahiservices.py:50
msgid "Error while resolving: "
msgstr "Fout tijdens het oplossen: "

#: avahiservices.py:105
msgid "Lost connection to avahi-daemon"
msgstr "Verbroken verbinding met avahi-daemon"

#: avahiservices.py:108
msgid "We are connected to avahi-daemon"
msgstr "Verbonden met avahi-daemon"

#: avahiservices.py:200
msgid "Can't remove service. That should not happen"
msgstr "Kan dienst niet verwijderen. Dit mag niet gebeuren"

#: avahiservices.py:220
#, python-format
msgid "Publishing service %s of type _sinerji._tcp"
msgstr "Publiceren van dienst %s van type _sinerji._tcp"

#: avahiservices.py:243
#, python-format
msgid "Error while adding service: %s"
msgstr "Fout tijdens toevoegen dienst: %s"

#: avahiservices.py:244 avahiservices.py:269
msgid "Local name collision"
msgstr "Lokale naamconflict"

#: avahiservices.py:250
msgid "Service successfully added"
msgstr "Dienst met succes toegevoegd"

#: avahiservices.py:253
msgid "Service successfully committed"
msgstr "Dienst met succes gecommitteerd"

#: avahiservices.py:256
#, python-format
msgid "Server state changed to %s"
msgstr "Status van dienst gewijzigd in %s"

#: avahiservices.py:264
msgid "CLIENT FAILURE"
msgstr "CLIENT-fout"

#: avahiservices.py:268
msgid "avahiservices.py: local name collision"
msgstr "avahiservices.py: lokale naamconflict"

#: avahiservices.py:273
msgid "avahiservices.py: ENTRY_GROUP_FAILURE reached (that should not happen)"
msgstr "avahiservices.py: ENTRY_GROUP_FAILURE opgetreden (dit mag niet gebeuren)"

#: disconnect.py:23 sinerji.py:204
#, python-format
msgid "%s is connected to you"
msgstr "%s is met hier verbonden"

#: sinerji.py:91
#, python-format
msgid "%s want to use your pc from %s"
msgstr "%s wil deze computer gebruiken vanaf %s"

#: sinerji.py:122
msgid "Manage"
msgstr "Beheer"

#: sinerji.py:126
msgid "About"
msgstr "Info over"

#: sinerji.py:132
msgid "Quit"
msgstr "Afsluiten"

#: sinerji.py:137
msgid "Disconnect"
msgstr "Verbreken"

#: sinerji.py:187
msgid "No Sinerji service available"
msgstr "Geen Sinerji-dienst beschikbaar"

#: sinerji.py:200
msgid "Start Synergyc"
msgstr "Synergyc starten"

#: sinerji.py:205
#, python-format
msgid "%s is connected to you."
msgstr "%s is met hier verbonden."

#: sinerji.py:216
#, python-format
msgid "Disconnected from %s"
msgstr "Niet verbonden met %s"

#: sinerji.py:223
msgid "Idle mode, nothing to do"
msgstr "Idle-modus, niets te doen"

#: sinerji.py:330
msgid "Synergy server started successfull"
msgstr "Synergy-dienst is met succes gestart"

#: sinerji.py:331
msgid "Synergy is connected to a pc"
msgstr "Synergy is verbonden met een computer"

#: sinerji.py:334
msgid "Warning"
msgstr "Waarschuwing"

#: sinerji.py:334
msgid "Somebody is using your computer. To use other computers please restart"
msgstr "Deze computer is reeds in gebruik. Herstart om deze computer te gebruiken"

#: sinerji.py:357
#, python-format
msgid "Computer %s is sharing its screen"
msgstr "Computer %s deelt zijn scherm"

#: sinerji.py:360
#, python-format
msgid "Computer %s is no longer sharing its screen"
msgstr "Computer %s deelt niet langerzijn scherm"

#: ui_sinerjigui.py:76
msgid "Choose the computer and his position to manage it"
msgstr "Selecteer de computer en zijn positie om het te beheren"

